name: docs_validate
on:
  pull_request:
    types: [opened, reopened, synchronize]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
permissions:
  contents: write
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - uses: actions/setup-node@v4
      - run: pip install mkdocs-material mkdocs-git-revision-date-localized-plugin mkdocs-glightbox
      - run: mkdocs build
        working-directory: docs
      - run: npm run mdlint
