name: notify
on:
  pull_request:
    types: [opened, reopened, closed]
jobs:
  notify:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Google Chat Notification
        uses: CommonMarvel/google-chat-notification@0e92788c236247c4051f873d60834a1214e4653f # ratchet:CommonMarvel/google-chat-notification@v1.2.1
        with:
          url: ${{ secrets.chat_webhook_url }}
